### ISSUE TITLE
sddpy violates license

### ISSUE THREAD

**Issue by odow** [wanqiuchansheng/sddpy#2]
SDDP.jl is licensed under MPL2.0: https://github.com/odow/SDDP.jl/blob/v0.0.2/LICENSE.md

If you copy it directly
https://github.com/wanqiuchansheng/sddpy/blob/cb131033c2d5eec4419fd3c435b974223fc32bbf/sddp/state.py#L10-L12
including the file structure

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/8177701/121766059-80721500-cba3-11eb-945b-c1128102b58b.png">
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/8177701/121766064-84059c00-cba3-11eb-82b6-fcbe33dbf7a5.png">

and the code is a direct translation from Python to Julia:

**sddpy**
<img width="806" alt="image" src="https://user-images.githubusercontent.com/8177701/121766219-a0ee9f00-cba4-11eb-8a56-a7bae54a2e57.png">
**SDDP.jl**
<img width="806" alt="image" src="https://user-images.githubusercontent.com/8177701/121766218-a0ee9f00-cba4-11eb-8c11-2241e449052d.png">
(including TODOs to make it more like SDDP.jl) then it is a derivative work. 

Therefore, you need to acknowledge where it came from (including keeping the copyright headers in each file) and release your code under the same license.

Please do one of the following:
- delete this repository
- re-instate the copyright headers and change the license to MPL2

**Comment by zzphd** [comment]
I'm sorry for the license violation. According to @odow 's advice, the copyright headers has been added to all the files and the license to has been changed to MPL2. Acknowledge and reference of the code have also been added.

**Comment by odow** [comment]
Thanks. Since you wrote the python code, you can add your name to the copyright headers. You just need to retain the original.
